substitutions:
  name: soyosource-gtn-display
  device_description: "Monitor and control the Soyosource GTN (Display version) using the internal display port"
  external_components_source: github://syssi/esphome-soyosource-gtn-virtual-meter@main
  # The internal display port should be connected to these GPIOs using a JST XH 2.54mm, 4 Pin connector (RX, TX, GND, VCC)
  # A optocoupler / optical isolator (f.e. ADUM1201) between the display port and the ESP is recommended if the ESP isn't powered by the display port!
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  friendly_name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-soyosource-gtn-virtual-meter"
    version: 2.5.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: INFO

api:
  reboot_timeout: 0s

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

soyosource_display:
  - id: display0
    uart_id: uart_0
    protocol_version: SOYOSOURCE_DISPLAY_VERSION
    update_interval: 5s

binary_sensor:
  - platform: soyosource_display
    fan_running:
      name: "fan running"
    limiter_connected:
      name: "limiter connected"

button:
  - platform: soyosource_display
    restart:
      name: "restart"

number:
  - platform: soyosource_display
    start_voltage:
      name: "start voltage"
    shutdown_voltage:
      name: "shutdown voltage"
    # Maximum output power in limiter mode / Output power in constant power mode
    output_power_limit:
      name: "output power limit"
    start_delay:
      name: "start delay"

select:
  - platform: soyosource_display
    operation_mode:
      name: "operation mode"
      optionsmap:
        1: "PV"
        2: "Battery Constant Power"
        16: "Battery Limit"

sensor:
  - platform: soyosource_display
    error_bitmask:
      name: "error bitmask"
    operation_mode_id:
      name: "operation mode id"
    operation_status_id:
      name: "operation status id"
      id: operation_status_id0
    battery_voltage:
      name: "battery voltage"
    battery_current:
      name: "battery current"
    battery_power:
      name: "battery power"
    ac_voltage:
      name: "ac voltage"
    ac_frequency:
      name: "ac frequency"
    temperature:
      name: "temperature"
    output_power:
      name: "output power"

text_sensor:
  - platform: soyosource_display
    errors:
      name: "errors"
    operation_mode:
      name: "operation mode"
    operation_status:
      name: "operation status"
