
http_request:
  useragent: esphome/device
  timeout: 5s

sensor:
  - platform: template
    id: powermeter
    name: "${name} instantaneous power"
    lambda: |-
      if (std::isnan(id(powermeter).state)) {
        return 0.0f;
      } else {
        return id(powermeter).state;
      }
    unit_of_measurement: W
    device_class: "power"
    accuracy_decimals: 2

time:
  - platform: sntp
    id: sntp_time
    on_time:
      - seconds: /1
        then:
          - http_request.get:
              url: http://192.168.132.5/status/
              headers:
                Content-Type: application/json
              verify_ssl: false
              on_response:
                then:
                  - lambda: |-
                      json::parse_json(id(http_request_data).get_string(), [](JsonObject root) {
                        id(powermeter).publish_state(root["total_power"]);
                      });
