# https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/discussions/137

substitutions:
  tasmota_status_url: "http://192.168.132.5/cm?cmnd=status+10"

http_request:
  id: http_request0
  useragent: esphome/device
  timeout: 1000ms
  verify_ssl: false

sensor:
  - platform: template
    id: powermeter0
    name: "Instantaneous Power"
    unit_of_measurement: W
    device_class: "power"
    state_class: measurement
    accuracy_decimals: 2
    update_interval: never

interval:
  - interval: 1100ms
    then:
      - http_request.get:
          url: ${tasmota_status_url}
          capture_response: true
          max_response_buffer_size: 2048
          request_headers:
            Content-Type: application/json
          on_response:
            then:
              - lambda: |-
                  if (response->status_code == 200 && !body.empty()) {
                    json::parse_json(body, [](JsonObject root) -> bool {
                      auto value = root["StatusSNS"]["SML"]["curr_w"];
                      if (!value.isNull()) {
                        id(powermeter0).publish_state(value.as<float>());
                        return true;
                      }
                      return false;
                    });
                  }
