# https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/discussions/137

substitutions:
  tasmota_status_url: "http://192.168.132.5/cm?cmnd=status+10"

http_request:
  id: http_request0
  useragent: esphome/device
  timeout: 1000ms
  verify_ssl: false

sensor:
  - platform: template
    id: powermeter0
    name: "Instantaneous Power"
    unit_of_measurement: W
    device_class: "power"
    accuracy_decimals: 2
    update_interval: never

interval:
  - interval: 1100ms
    then:
      - http_request.get:
          url: ${tasmota_status_url}
          request_headers:
            Content-Type: application/json
          on_response:
            then:
              - lambda: |-
                  std::string response_data = id(http_request0).get_string();
                  if(!response_data.empty()) {
                    json::parse_json(response_data, [](JsonObject root) {
                      id(powermeter0).publish_state(root["StatusSNS"]["SML"]["Leistung"]);
                    });
                  }
